login_txt_username = 'login_input_Username'
login_label_appName = 'auth_text_AppName'
login_btn_changelanguage = 'auth_btn_ChangeLanguage'
login_txt_username_inactive = 'login_input_Username-label-inactive'
login_txt_password_inactive = 'login_input_Password-label-inactive'
login_btn_forgotpass = "login_btn_ForgotPassword"
login_label_login = 'login_text_Login'
login_txt_password = 'login_input_Password'
login_btn_login = 'login_btn_Login'
login_dashboard_screen = '(//android.widget.TextView[@text="Dashboard"])[1]'
login_fail_password_error = '//android.widget.TextView[@text="Sai thông tin đăng nhập. Vui lòng kiểm tra lại thông tin đăng nhập!"]'
login_fail_password_error_en = '//android.widget.TextView[@text="Wrong username or password. Please try again!"]'
login_fail_username_error_1 = '//android.widget.TextView[@text="Tài khoản không tồn tại. Vui lòng liên hệ với Quản trị viên!"]'
login_fail_username_error_1_en = '//android.widget.TextView[@text="Username is not found. Please contact the Administrator!"]'
login_fail_account_disable = '//android.widget.TextView[@text="Tài khoản đã bị vô hiệu hóa. Vui lòng liên hệ với Quản trị viên!"]'
login_fail_account_disable_en = '//android.widget.TextView[@text="Your account has been inactive. Please contact the Administrator!"]'
login_fail_error_2 = '//android.widget.TextView[@text="Đã Xảy Ra Lỗi"]'
login_fail_error_2_en = '//android.widget.TextView[@text="An error occurred"]'
login_empty_username_error = 'login_text_UsernameError'
login_empty_password_error = 'login_text_PasswordError'
logout_btn = 'account_text_Logout'