login_txt_username = 'login_input_Username'
login_label_login = 'login_text_Login'
login_txt_password = 'login_input_Password'
login_btn_login = 'login_btn_Login'
login_dashboard_screen = '(//android.widget.TextView[@text="Dashboard"])[1]'
login_fail_password_error = '//android.widget.TextView[@text="Sai thông tin đăng nhập. Vui lòng kiểm tra lại thông tin đăng nhập!"]'
login_fail_username_error_1 = '//android.widget.TextView[@text="Tài khoản không tồn tại. Vui lòng liên hệ với Quản trị viên!"]'
login_fail_error_2 = '//android.widget.TextView[@text="Đã Xảy Ra Lỗi"]'
login_empty_username_error = '(//android.widget.EditText[@resource-id="text-input-outlined"]/following::android.widget.TextView[@text="*Vui lòng nhập trường này!"])[1]'
login_empty_password_error = '(//android.widget.EditText[@resource-id="text-input-outlined"]/following::android.widget.TextView[@text="*Vui lòng nhập trường này!"])[2]'
login_empty_error = '//android.widget.TextView[@text="*Vui lòng nhập trường này!"]'
logout_btn = 'account_text_Logout'