login_txt_username = '(//android.widget.EditText[@resource-id="text-input-outlined"])[1]'
login_txt_password = '(//android.widget.EditText[@resource-id="text-input-outlined"])[2]'
login_btn_login = '//android.widget.Button[@content-desc="Đăng nhập"]'
login_dashboard_screen = '(//android.widget.TextView[@text="Dashboard"])[1]'
login_fail_error = '//android.widget.TextView[@text="Sai thông tin đăng nhập. Vui lòng kiểm tra lại thông tin đăng nhập!"]'
login_empty_username_error = '(//android.widget.EditText[@resource-id="text-input-outlined"]/following::android.widget.TextView[@text="*Vui lòng nhập trường này!"])[1]'
login_empty_password_error = '(//android.widget.EditText[@resource-id="text-input-outlined"]/following::android.widget.TextView[@text="*Vui lòng nhập trường này!"])[2]'
login_empty_error = '(//android.widget.EditText[@resource-id="text-input-outlined"]/following::android.widget.TextView[@text="*Vui lòng nhập trường này!"])[1]'